<?php

namespace Database\Seeders;

use App\Models\WatsonDestination;
use Illuminate\Database\Seeder;

class WatsonDestinationSeeder extends Seeder
{
    /**
     * Seeds the Watson destination rate card from WATSONS_RATE_COPY.xlsx.
     *
     * Source sheet has 3 sections:
     *  - Provincial destinations with 6W / 4W / AUV rates each
     *  - Metro Manila "AUV" rates (Origin: PMP)
     *  - Metro Manila "4WCV" rates, labelled "4WHLR RATE" (Origin: PMP), mapped to truck_type '4W'
     *
     * 3 exact duplicate rows in the source sheet were removed
     * (Bulacan - San Jose Del Monte, Isabela - Cauayan City, Pangasinan - Dagupan).
     */
    public function run(): void
    {
        $rows = [
            ['origin' => null, 'destination_name' => 'BAGUIO', 'area' => null, 'truck_type' => '6W', 'rate' => 9505.0],
            ['origin' => null, 'destination_name' => 'BAGUIO', 'area' => null, 'truck_type' => '4W', 'rate' => 8382.0],
            ['origin' => null, 'destination_name' => 'BAGUIO', 'area' => null, 'truck_type' => 'AUV', 'rate' => 6208.0],
            ['origin' => null, 'destination_name' => 'DINALUPIHAN', 'area' => 'BATAAN', 'truck_type' => '6W', 'rate' => 5295.0],
            ['origin' => null, 'destination_name' => 'DINALUPIHAN', 'area' => 'BATAAN', 'truck_type' => '4W', 'rate' => 4221.0],
            ['origin' => null, 'destination_name' => 'DINALUPIHAN', 'area' => 'BATAAN', 'truck_type' => 'AUV', 'rate' => 3926.0],
            ['origin' => null, 'destination_name' => 'ORANI CITY', 'area' => 'BATAAN', 'truck_type' => '6W', 'rate' => 5298.0],
            ['origin' => null, 'destination_name' => 'ORANI CITY', 'area' => 'BATAAN', 'truck_type' => '4W', 'rate' => 4151.0],
            ['origin' => null, 'destination_name' => 'ORANI CITY', 'area' => 'BATAAN', 'truck_type' => 'AUV', 'rate' => 4225.0],
            ['origin' => null, 'destination_name' => 'LA TRINIDAD', 'area' => 'BENGUET', 'truck_type' => '6W', 'rate' => 9750.0],
            ['origin' => null, 'destination_name' => 'LA TRINIDAD', 'area' => 'BENGUET', 'truck_type' => '4W', 'rate' => 8815.0],
            ['origin' => null, 'destination_name' => 'LA TRINIDAD', 'area' => 'BENGUET', 'truck_type' => 'AUV', 'rate' => 6358.0],
            ['origin' => null, 'destination_name' => 'BALIWAG', 'area' => 'BULACAN', 'truck_type' => '6W', 'rate' => 4235.0],
            ['origin' => null, 'destination_name' => 'BALIWAG', 'area' => 'BULACAN', 'truck_type' => '4W', 'rate' => 3879.0],
            ['origin' => null, 'destination_name' => 'BALIWAG', 'area' => 'BULACAN', 'truck_type' => 'AUV', 'rate' => 3043.0],
            ['origin' => null, 'destination_name' => 'MALOLOS', 'area' => 'BULACAN', 'truck_type' => '6W', 'rate' => 4569.0],
            ['origin' => null, 'destination_name' => 'MALOLOS', 'area' => 'BULACAN', 'truck_type' => '4W', 'rate' => 4133.0],
            ['origin' => null, 'destination_name' => 'MALOLOS', 'area' => 'BULACAN', 'truck_type' => 'AUV', 'rate' => 3247.0],
            ['origin' => null, 'destination_name' => 'MARILAO', 'area' => 'BULACAN', 'truck_type' => '6W', 'rate' => 4725.0],
            ['origin' => null, 'destination_name' => 'MARILAO', 'area' => 'BULACAN', 'truck_type' => '4W', 'rate' => 4251.0],
            ['origin' => null, 'destination_name' => 'MARILAO', 'area' => 'BULACAN', 'truck_type' => 'AUV', 'rate' => 3342.0],
            ['origin' => null, 'destination_name' => 'MEYCAUAYAN', 'area' => 'BULACAN', 'truck_type' => '6W', 'rate' => 4725.0],
            ['origin' => null, 'destination_name' => 'MEYCAUAYAN', 'area' => 'BULACAN', 'truck_type' => '4W', 'rate' => 4251.0],
            ['origin' => null, 'destination_name' => 'MEYCAUAYAN', 'area' => 'BULACAN', 'truck_type' => 'AUV', 'rate' => 3342.0],
            ['origin' => null, 'destination_name' => 'OBANDO', 'area' => 'BULACAN', 'truck_type' => '6W', 'rate' => 4858.0],
            ['origin' => null, 'destination_name' => 'OBANDO', 'area' => 'BULACAN', 'truck_type' => '4W', 'rate' => 4352.0],
            ['origin' => null, 'destination_name' => 'OBANDO', 'area' => 'BULACAN', 'truck_type' => 'AUV', 'rate' => 3424.0],
            ['origin' => null, 'destination_name' => 'PLARIDEL', 'area' => 'BULACAN', 'truck_type' => '6W', 'rate' => 4368.0],
            ['origin' => null, 'destination_name' => 'PLARIDEL', 'area' => 'BULACAN', 'truck_type' => '4W', 'rate' => 3981.0],
            ['origin' => null, 'destination_name' => 'PLARIDEL', 'area' => 'BULACAN', 'truck_type' => 'AUV', 'rate' => 3124.0],
            ['origin' => null, 'destination_name' => 'SAN ILDEFONSO', 'area' => 'BULACAN', 'truck_type' => '6W', 'rate' => 4881.0],
            ['origin' => null, 'destination_name' => 'SAN ILDEFONSO', 'area' => 'BULACAN', 'truck_type' => '4W', 'rate' => 4369.0],
            ['origin' => null, 'destination_name' => 'SAN ILDEFONSO', 'area' => 'BULACAN', 'truck_type' => 'AUV', 'rate' => 3417.0],
            ['origin' => null, 'destination_name' => 'SAN JOSE DEL MONTE', 'area' => 'BULACAN', 'truck_type' => '6W', 'rate' => 4836.0],
            ['origin' => null, 'destination_name' => 'SAN JOSE DEL MONTE', 'area' => 'BULACAN', 'truck_type' => '4W', 'rate' => 4336.0],
            ['origin' => null, 'destination_name' => 'SAN JOSE DEL MONTE', 'area' => 'BULACAN', 'truck_type' => 'AUV', 'rate' => 3410.0],
            ['origin' => null, 'destination_name' => 'SAN MIGUEL', 'area' => 'BULACAN', 'truck_type' => '6W', 'rate' => 4836.0],
            ['origin' => null, 'destination_name' => 'SAN MIGUEL', 'area' => 'BULACAN', 'truck_type' => '4W', 'rate' => 4336.0],
            ['origin' => null, 'destination_name' => 'SAN MIGUEL', 'area' => 'BULACAN', 'truck_type' => 'AUV', 'rate' => 3410.0],
            ['origin' => null, 'destination_name' => 'STA. MARIA', 'area' => 'BULACAN', 'truck_type' => '6W', 'rate' => 4702.0],
            ['origin' => null, 'destination_name' => 'STA. MARIA', 'area' => 'BULACAN', 'truck_type' => '4W', 'rate' => 4234.0],
            ['origin' => null, 'destination_name' => 'STA. MARIA', 'area' => 'BULACAN', 'truck_type' => 'AUV', 'rate' => 3328.0],
            ['origin' => null, 'destination_name' => 'AMULUNG', 'area' => 'CAGAYAN', 'truck_type' => '6W', 'rate' => 18339.0],
            ['origin' => null, 'destination_name' => 'AMULUNG', 'area' => 'CAGAYAN', 'truck_type' => '4W', 'rate' => 13780.0],
            ['origin' => null, 'destination_name' => 'AMULUNG', 'area' => 'CAGAYAN', 'truck_type' => 'AUV', 'rate' => 12112.0],
            ['origin' => null, 'destination_name' => 'TUGUEGARAO', 'area' => 'CAGAYAN', 'truck_type' => '6W', 'rate' => 15426.0],
            ['origin' => null, 'destination_name' => 'TUGUEGARAO', 'area' => 'CAGAYAN', 'truck_type' => '4W', 'rate' => 12250.0],
            ['origin' => null, 'destination_name' => 'TUGUEGARAO', 'area' => 'CAGAYAN', 'truck_type' => 'AUV', 'rate' => 10719.0],
            ['origin' => null, 'destination_name' => 'BATAC', 'area' => 'ILOCOS NORTE', 'truck_type' => '6W', 'rate' => 16248.0],
            ['origin' => null, 'destination_name' => 'BATAC', 'area' => 'ILOCOS NORTE', 'truck_type' => '4W', 'rate' => 12701.0],
            ['origin' => null, 'destination_name' => 'BATAC', 'area' => 'ILOCOS NORTE', 'truck_type' => 'AUV', 'rate' => 10558.0],
            ['origin' => null, 'destination_name' => 'LAOAG', 'area' => 'ILOCOS NORTE', 'truck_type' => '6W', 'rate' => 16292.0],
            ['origin' => null, 'destination_name' => 'LAOAG', 'area' => 'ILOCOS NORTE', 'truck_type' => '4W', 'rate' => 12735.0],
            ['origin' => null, 'destination_name' => 'LAOAG', 'area' => 'ILOCOS NORTE', 'truck_type' => 'AUV', 'rate' => 10586.0],
            ['origin' => null, 'destination_name' => 'SAN NICOLAS', 'area' => 'ILOCOS NORTE', 'truck_type' => '6W', 'rate' => 16248.0],
            ['origin' => null, 'destination_name' => 'SAN NICOLAS', 'area' => 'ILOCOS NORTE', 'truck_type' => '4W', 'rate' => 12701.0],
            ['origin' => null, 'destination_name' => 'SAN NICOLAS', 'area' => 'ILOCOS NORTE', 'truck_type' => 'AUV', 'rate' => 10558.0],
            ['origin' => null, 'destination_name' => 'NARVACAN', 'area' => 'ILOCOS SUR', 'truck_type' => '6W', 'rate' => 14324.0],
            ['origin' => null, 'destination_name' => 'NARVACAN', 'area' => 'ILOCOS SUR', 'truck_type' => '4W', 'rate' => 10171.0],
            ['origin' => null, 'destination_name' => 'NARVACAN', 'area' => 'ILOCOS SUR', 'truck_type' => 'AUV', 'rate' => 8744.0],
            ['origin' => null, 'destination_name' => 'VIGAN', 'area' => 'ILOCOS SUR', 'truck_type' => '6W', 'rate' => 14532.0],
            ['origin' => null, 'destination_name' => 'VIGAN', 'area' => 'ILOCOS SUR', 'truck_type' => '4W', 'rate' => 12801.0],
            ['origin' => null, 'destination_name' => 'VIGAN', 'area' => 'ILOCOS SUR', 'truck_type' => 'AUV', 'rate' => 9044.0],
            ['origin' => null, 'destination_name' => 'AURORA', 'area' => 'ISABELA', 'truck_type' => '6W', 'rate' => 13555.0],
            ['origin' => null, 'destination_name' => 'AURORA', 'area' => 'ISABELA', 'truck_type' => '4W', 'rate' => 9936.0],
            ['origin' => null, 'destination_name' => 'AURORA', 'area' => 'ISABELA', 'truck_type' => 'AUV', 'rate' => 8109.0],
            ['origin' => null, 'destination_name' => 'CABAGAN', 'area' => 'ISABELA', 'truck_type' => '6W', 'rate' => 15047.0],
            ['origin' => null, 'destination_name' => 'CABAGAN', 'area' => 'ISABELA', 'truck_type' => '4W', 'rate' => 11982.0],
            ['origin' => null, 'destination_name' => 'CABAGAN', 'area' => 'ISABELA', 'truck_type' => 'AUV', 'rate' => 9888.0],
            ['origin' => null, 'destination_name' => 'CAUAYAN CITY', 'area' => 'ISABELA', 'truck_type' => '6W', 'rate' => 13599.0],
            ['origin' => null, 'destination_name' => 'CAUAYAN CITY', 'area' => 'ISABELA', 'truck_type' => '4W', 'rate' => 9370.0],
            ['origin' => null, 'destination_name' => 'CAUAYAN CITY', 'area' => 'ISABELA', 'truck_type' => 'AUV', 'rate' => 7737.0],
            ['origin' => null, 'destination_name' => 'AGOO', 'area' => 'LA UNION', 'truck_type' => '6W', 'rate' => 9973.0],
            ['origin' => null, 'destination_name' => 'AGOO', 'area' => 'LA UNION', 'truck_type' => '4W', 'rate' => 8984.0],
            ['origin' => null, 'destination_name' => 'AGOO', 'area' => 'LA UNION', 'truck_type' => 'AUV', 'rate' => 5994.0],
            ['origin' => null, 'destination_name' => 'SAN FERNANDO', 'area' => 'LA UNION', 'truck_type' => '6W', 'rate' => 9973.0],
            ['origin' => null, 'destination_name' => 'SAN FERNANDO', 'area' => 'LA UNION', 'truck_type' => '4W', 'rate' => 8984.0],
            ['origin' => null, 'destination_name' => 'SAN FERNANDO', 'area' => 'LA UNION', 'truck_type' => 'AUV', 'rate' => 5994.0],
            ['origin' => null, 'destination_name' => 'CABANATUAN', 'area' => 'NUEVA ECIJA', 'truck_type' => '6W', 'rate' => 5176.0],
            ['origin' => null, 'destination_name' => 'CABANATUAN', 'area' => 'NUEVA ECIJA', 'truck_type' => '4W', 'rate' => 4615.0],
            ['origin' => null, 'destination_name' => 'CABANATUAN', 'area' => 'NUEVA ECIJA', 'truck_type' => 'AUV', 'rate' => 4400.0],
            ['origin' => null, 'destination_name' => 'GAPAN', 'area' => 'NUEVA ECIJA', 'truck_type' => '6W', 'rate' => 5106.0],
            ['origin' => null, 'destination_name' => 'GAPAN', 'area' => 'NUEVA ECIJA', 'truck_type' => '4W', 'rate' => 4638.0],
            ['origin' => null, 'destination_name' => 'GAPAN', 'area' => 'NUEVA ECIJA', 'truck_type' => 'AUV', 'rate' => 4073.0],
            ['origin' => null, 'destination_name' => 'SANTA ROSA', 'area' => 'NUEVA ECIJA', 'truck_type' => '6W', 'rate' => 5150.0],
            ['origin' => null, 'destination_name' => 'SANTA ROSA', 'area' => 'NUEVA ECIJA', 'truck_type' => '4W', 'rate' => 4371.0],
            ['origin' => null, 'destination_name' => 'SANTA ROSA', 'area' => 'NUEVA ECIJA', 'truck_type' => 'AUV', 'rate' => 4136.0],
            ['origin' => null, 'destination_name' => 'TALAVERA', 'area' => 'NUEVA ECIJA', 'truck_type' => '6W', 'rate' => 6518.0],
            ['origin' => null, 'destination_name' => 'TALAVERA', 'area' => 'NUEVA ECIJA', 'truck_type' => '4W', 'rate' => 4635.0],
            ['origin' => null, 'destination_name' => 'TALAVERA', 'area' => 'NUEVA ECIJA', 'truck_type' => 'AUV', 'rate' => 4577.0],
            ['origin' => null, 'destination_name' => 'ZARAGOSA', 'area' => 'NUEVA ECIJA', 'truck_type' => '6W', 'rate' => 5166.0],
            ['origin' => null, 'destination_name' => 'ZARAGOSA', 'area' => 'NUEVA ECIJA', 'truck_type' => '4W', 'rate' => 4471.0],
            ['origin' => null, 'destination_name' => 'ZARAGOSA', 'area' => 'NUEVA ECIJA', 'truck_type' => 'AUV', 'rate' => 4436.0],
            ['origin' => null, 'destination_name' => 'BAMBANG', 'area' => 'NUEVA VIZCAYA', 'truck_type' => '6W', 'rate' => 10414.0],
            ['origin' => null, 'destination_name' => 'BAMBANG', 'area' => 'NUEVA VIZCAYA', 'truck_type' => '4W', 'rate' => 8199.0],
            ['origin' => null, 'destination_name' => 'BAMBANG', 'area' => 'NUEVA VIZCAYA', 'truck_type' => 'AUV', 'rate' => 6871.0],
            ['origin' => null, 'destination_name' => 'ANGELES', 'area' => 'PAMPANGA', 'truck_type' => '6W', 'rate' => 3753.0],
            ['origin' => null, 'destination_name' => 'ANGELES', 'area' => 'PAMPANGA', 'truck_type' => '4W', 'rate' => 3528.0],
            ['origin' => null, 'destination_name' => 'ANGELES', 'area' => 'PAMPANGA', 'truck_type' => 'AUV', 'rate' => 2848.0],
            ['origin' => null, 'destination_name' => 'CLARK ANGELES', 'area' => 'PAMPANGA', 'truck_type' => '6W', 'rate' => 4087.0],
            ['origin' => null, 'destination_name' => 'CLARK ANGELES', 'area' => 'PAMPANGA', 'truck_type' => '4W', 'rate' => 3781.0],
            ['origin' => null, 'destination_name' => 'CLARK ANGELES', 'area' => 'PAMPANGA', 'truck_type' => 'AUV', 'rate' => 2552.0],
            ['origin' => null, 'destination_name' => 'MABALACAT', 'area' => 'PAMPANGA', 'truck_type' => '6W', 'rate' => 4087.0],
            ['origin' => null, 'destination_name' => 'MABALACAT', 'area' => 'PAMPANGA', 'truck_type' => '4W', 'rate' => 3781.0],
            ['origin' => null, 'destination_name' => 'MABALACAT', 'area' => 'PAMPANGA', 'truck_type' => 'AUV', 'rate' => 2552.0],
            ['origin' => null, 'destination_name' => 'MACABEBE', 'area' => 'PAMPANGA', 'truck_type' => '6W', 'rate' => 4019.0],
            ['origin' => null, 'destination_name' => 'MACABEBE', 'area' => 'PAMPANGA', 'truck_type' => '4W', 'rate' => 3826.0],
            ['origin' => null, 'destination_name' => 'MACABEBE', 'area' => 'PAMPANGA', 'truck_type' => 'AUV', 'rate' => 2667.0],
            ['origin' => null, 'destination_name' => 'MAGALANG', 'area' => 'PAMPANGA', 'truck_type' => '6W', 'rate' => 4019.0],
            ['origin' => null, 'destination_name' => 'MAGALANG', 'area' => 'PAMPANGA', 'truck_type' => '4W', 'rate' => 3826.0],
            ['origin' => null, 'destination_name' => 'MAGALANG', 'area' => 'PAMPANGA', 'truck_type' => 'AUV', 'rate' => 2667.0],
            ['origin' => null, 'destination_name' => 'SAN FERNANDO', 'area' => 'PAMPANGA', 'truck_type' => '6W', 'rate' => 3575.0],
            ['origin' => null, 'destination_name' => 'SAN FERNANDO', 'area' => 'PAMPANGA', 'truck_type' => '4W', 'rate' => 3393.0],
            ['origin' => null, 'destination_name' => 'SAN FERNANDO', 'area' => 'PAMPANGA', 'truck_type' => 'AUV', 'rate' => 2439.0],
            ['origin' => null, 'destination_name' => 'BOLINAO', 'area' => 'PANGASINAN', 'truck_type' => '6W', 'rate' => 8970.0],
            ['origin' => null, 'destination_name' => 'BOLINAO', 'area' => 'PANGASINAN', 'truck_type' => '4W', 'rate' => 7600.0],
            ['origin' => null, 'destination_name' => 'BOLINAO', 'area' => 'PANGASINAN', 'truck_type' => 'AUV', 'rate' => 5680.0],
            ['origin' => null, 'destination_name' => 'CALASIAO & ROSALES', 'area' => 'PANGASINAN', 'truck_type' => '6W', 'rate' => 8018.0],
            ['origin' => null, 'destination_name' => 'CALASIAO & ROSALES', 'area' => 'PANGASINAN', 'truck_type' => '4W', 'rate' => 6704.0],
            ['origin' => null, 'destination_name' => 'CALASIAO & ROSALES', 'area' => 'PANGASINAN', 'truck_type' => 'AUV', 'rate' => 4958.0],
            ['origin' => null, 'destination_name' => 'DAGUPAN', 'area' => 'PANGASINAN', 'truck_type' => '6W', 'rate' => 8263.0],
            ['origin' => null, 'destination_name' => 'DAGUPAN', 'area' => 'PANGASINAN', 'truck_type' => '4W', 'rate' => 7138.0],
            ['origin' => null, 'destination_name' => 'DAGUPAN', 'area' => 'PANGASINAN', 'truck_type' => 'AUV', 'rate' => 5108.0],
            ['origin' => null, 'destination_name' => 'MALASIQUI', 'area' => 'PANGASINAN', 'truck_type' => '6W', 'rate' => 7414.0],
            ['origin' => null, 'destination_name' => 'MALASIQUI', 'area' => 'PANGASINAN', 'truck_type' => '4W', 'rate' => 6434.0],
            ['origin' => null, 'destination_name' => 'MALASIQUI', 'area' => 'PANGASINAN', 'truck_type' => 'AUV', 'rate' => 4617.0],
            ['origin' => null, 'destination_name' => 'TAYUG', 'area' => 'PANGASINAN', 'truck_type' => '6W', 'rate' => 7570.0],
            ['origin' => null, 'destination_name' => 'TAYUG', 'area' => 'PANGASINAN', 'truck_type' => '4W', 'rate' => 6852.0],
            ['origin' => null, 'destination_name' => 'TAYUG', 'area' => 'PANGASINAN', 'truck_type' => 'AUV', 'rate' => 4712.0],
            ['origin' => null, 'destination_name' => 'URDANETA', 'area' => 'PANGASINAN', 'truck_type' => '6W', 'rate' => 7369.0],
            ['origin' => null, 'destination_name' => 'URDANETA', 'area' => 'PANGASINAN', 'truck_type' => '4W', 'rate' => 7200.0],
            ['origin' => null, 'destination_name' => 'URDANETA', 'area' => 'PANGASINAN', 'truck_type' => 'AUV', 'rate' => 5390.0],
            ['origin' => null, 'destination_name' => 'CAMILING', 'area' => 'TARLAC', 'truck_type' => '6W', 'rate' => 5988.0],
            ['origin' => null, 'destination_name' => 'CAMILING', 'area' => 'TARLAC', 'truck_type' => '4W', 'rate' => 5366.0],
            ['origin' => null, 'destination_name' => 'CAMILING', 'area' => 'TARLAC', 'truck_type' => 'AUV', 'rate' => 4111.0],
            ['origin' => null, 'destination_name' => 'CAPAS', 'area' => 'TARLAC', 'truck_type' => '6W', 'rate' => 5396.0],
            ['origin' => null, 'destination_name' => 'CAPAS', 'area' => 'TARLAC', 'truck_type' => '4W', 'rate' => 4724.0],
            ['origin' => null, 'destination_name' => 'CAPAS', 'area' => 'TARLAC', 'truck_type' => 'AUV', 'rate' => 3593.0],
            ['origin' => null, 'destination_name' => 'CONCEPCION', 'area' => 'TARLAC', 'truck_type' => '6W', 'rate' => 5396.0],
            ['origin' => null, 'destination_name' => 'CONCEPCION', 'area' => 'TARLAC', 'truck_type' => '4W', 'rate' => 4724.0],
            ['origin' => null, 'destination_name' => 'CONCEPCION', 'area' => 'TARLAC', 'truck_type' => 'AUV', 'rate' => 3593.0],
            ['origin' => null, 'destination_name' => 'OLONGAPO', 'area' => 'ZAMBALES', 'truck_type' => '6W', 'rate' => 5498.0],
            ['origin' => null, 'destination_name' => 'OLONGAPO', 'area' => 'ZAMBALES', 'truck_type' => '4W', 'rate' => 4429.0],
            ['origin' => null, 'destination_name' => 'OLONGAPO', 'area' => 'ZAMBALES', 'truck_type' => 'AUV', 'rate' => 4225.0],
            ['origin' => null, 'destination_name' => 'STA. CRUZ', 'area' => 'ZAMBALES', 'truck_type' => '6W', 'rate' => 8094.0],
            ['origin' => null, 'destination_name' => 'STA. CRUZ', 'area' => 'ZAMBALES', 'truck_type' => '4W', 'rate' => 6877.0],
            ['origin' => null, 'destination_name' => 'STA. CRUZ', 'area' => 'ZAMBALES', 'truck_type' => 'AUV', 'rate' => 5792.0],
            ['origin' => null, 'destination_name' => 'SUBIC', 'area' => 'ZAMBALES', 'truck_type' => '6W', 'rate' => 5398.0],
            ['origin' => null, 'destination_name' => 'SUBIC', 'area' => 'ZAMBALES', 'truck_type' => '4W', 'rate' => 4349.0],
            ['origin' => null, 'destination_name' => 'SUBIC', 'area' => 'ZAMBALES', 'truck_type' => 'AUV', 'rate' => 4389.0],
            ['origin' => 'PMP', 'destination_name' => 'CENTRAL (QUEZON CITY)', 'area' => 'METRO MANILA', 'truck_type' => 'AUV', 'rate' => 3607.0],
            ['origin' => 'PMP', 'destination_name' => 'MAKATI', 'area' => 'METRO MANILA', 'truck_type' => 'AUV', 'rate' => 3824.0],
            ['origin' => 'PMP', 'destination_name' => 'TAGUIG', 'area' => 'METRO MANILA', 'truck_type' => 'AUV', 'rate' => 3850.0],
            ['origin' => 'PMP', 'destination_name' => 'CALOOCAN', 'area' => 'METRO MANILA', 'truck_type' => 'AUV', 'rate' => 3457.0],
            ['origin' => 'PMP', 'destination_name' => 'CAINTA', 'area' => 'METRO MANILA', 'truck_type' => 'AUV', 'rate' => 3876.0],
            ['origin' => 'PMP', 'destination_name' => 'PASIG', 'area' => 'METRO MANILA', 'truck_type' => 'AUV', 'rate' => 3876.0],
            ['origin' => 'PMP', 'destination_name' => 'PASAY', 'area' => 'METRO MANILA', 'truck_type' => 'AUV', 'rate' => 4013.0],
            ['origin' => 'PMP', 'destination_name' => 'MANILA', 'area' => 'METRO MANILA', 'truck_type' => 'AUV', 'rate' => 3835.0],
            ['origin' => 'PMP', 'destination_name' => 'CENTRAL (QUEZON CITY)', 'area' => 'METRO MANILA', 'truck_type' => '4W', 'rate' => 4222.0],
            ['origin' => 'PMP', 'destination_name' => 'MAKATI', 'area' => 'METRO MANILA', 'truck_type' => '4W', 'rate' => 4429.0],
            ['origin' => 'PMP', 'destination_name' => 'TAGUIG', 'area' => 'METRO MANILA', 'truck_type' => '4W', 'rate' => 4450.0],
            ['origin' => 'PMP', 'destination_name' => 'CALOOCAN', 'area' => 'METRO MANILA', 'truck_type' => '4W', 'rate' => 3913.0],
            ['origin' => 'PMP', 'destination_name' => 'CAINTA', 'area' => 'METRO MANILA', 'truck_type' => '4W', 'rate' => 4221.0],
            ['origin' => 'PMP', 'destination_name' => 'PASIG', 'area' => 'METRO MANILA', 'truck_type' => '4W', 'rate' => 4221.0],
            ['origin' => 'PMP', 'destination_name' => 'PASAY', 'area' => 'METRO MANILA', 'truck_type' => '4W', 'rate' => 4771.0],
            ['origin' => 'PMP', 'destination_name' => 'MANILA', 'area' => 'METRO MANILA', 'truck_type' => '4W', 'rate' => 4411.0],
        ];

        foreach ($rows as $row) {
            WatsonDestination::updateOrCreate(
                [
                    'origin' => $row['origin'],
                    'destination_name' => $row['destination_name'],
                    'truck_type' => $row['truck_type'],
                ],
                [
                    'area' => $row['area'],
                    'rate' => $row['rate'],
                ]
            );
        }
    }
}
